version: 3
# workflows:
#   my-workflow:
#     jobs:
#       - build:
#           context:
#             - build-env-vars
#             - docker-hub-creds
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:20.10.12-git
        auth:
          username: marianodacosta # can specify string literal values
          password: Rfn##9ri33C@ # or project environment variable reference
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py3-pip=20.3.4-r1
            pip install docker-compose==2.2.1
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
